### ISSUE TITLE
Linux executable doesn't start if under a path with spaces

### ISSUE THREAD

**Issue by salmonb** [fvarrui/JavaPackager#214] opened 2022-07-03 11:16 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

If the path to the repository contains spaces, the Linux executable generated by Javapackager doesn't start.

**Steps to reproduce the issue/enhancement:**

1. Create a directory with spaces (ex: `mkdir My\ Projects`)
2. Move the project under that directory
3. Try to run the executable generated by Javapackager

**What is the expected behavior?**

The executable should run, whether or not there are spaces in the path

**What is the current behavior?**

The executable fails to run when there are spaces in the path

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

```
$ /home/bruno/My\ Projects/myproject/mymodule/target/javapackager/MyApp/MyApp
/home/bruno/My Projects/myproject/mymodule/target/javapackager/MyApp/MyApp: line 13: [: /home/bruno: binary operator expected
/home/bruno/My Projects/myproject/mymodule/target/javapackager/MyApp/MyApp: line 17: cd: $'/home/bruno\nProjects/myproject/mymodule/target/javapackager/MyApp': No such file or directory
/home/bruno/My Projects/myproject/mymodule/target/javapackager/MyApp/MyApp: line 20: /home/bruno: Is a directory
```

**What is the motivation / use case for changing the behavior?**

Just make it works :)

**Please tell us about your environment:**

- JavaPackager version: 1.6.6
- OS version: Ubuntu 22.04
- JDK version: openjdk version "18.0.1.1" 2022-04-22
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by salmonb** [comment] 2022-07-12 17:34
hi @fvarrui 

Here is the content of startup.sh

```
#!/usr/bin/env bash
# GNU/Linux startup script generated by JavaPackager plugin

SCRIPTPATH=$(dirname $(readlink -e "$0"))

JAVA="$SCRIPTPATH/jre/bin/java"

BINARY="$SCRIPTPATH/WebFXExample"


JVMDefaultOptions=""
JVMOptionsFile="$SCRIPTPATH/WebFXExample.l4j.ini"
[ -f $JVMOptionsFile ] && while read -r option; do JVMDefaultOptions+=" $option"; done <<< $(sed "/^#.*$/d" $JVMOptionsFile)

JVMClassPath="$BINARY"

cd "$SCRIPTPATH"


$JAVA $JVMDefaultOptions -cp $JVMClassPath dev.webfx.platform.boot.ApplicationBooter $@
exit 0
```

If I run this script under a path with a space (ex: /home/bruno/dev/javapackager\ issue/... <= there is a space between javapackager and issue), then I'm getting this error:

```
./startup.sh: line 13: [: /home/bruno/dev: binary operator expected
./startup.sh: line 17: cd: $'/home/bruno/dev\nissue/webfx-example-application-openjfx/target/javapackager/assets': No such file or directory
```

**Comment by fvarrui** [comment] 2022-07-12 17:38
Yes, thank you! I'm working on it ... I've just reproduced your issue and find out that the problem is in this line:

```bash
SCRIPTPATH=$(dirname $(readlink -e "$0"))
```

Just adding doublequotes and the problem is fixed:

```bash
SCRIPTPATH=$(dirname "$(readlink -e "$0")")
```

> Notice the double quotes

I've just released the change in issue-214 ... please, try it and give me some feedback. I'd like to include this fix in v1.6.7.

**Comment by fvarrui** [comment] 2022-07-12 17:40
AppImage generation feature is already included ... as you are trying on Linux, would you mind trying the `AppImage` binary too?

**Comment by salmonb** [comment] 2022-07-12 18:31
Great, glad that you found a fix :smiley: 

I'm happy to test, but not sure how, as I never used a Maven plugin other than by listing it on my pom.xml...

I cloned your repository and checked out the issue-214 branch, but how can I tell Maven to use it now?
I'm not used to Maven plugin development, sorry...

**Comment by fvarrui** [comment] 2022-07-13 10:43
Hi @salmonb!

You can build JavaPackager on your own by running next commands:

```bash
git clone https://github.com/fvarrui/JavaPackager --branch devel
cd JavaPackager
./gradlew publishToMavenLocal
```
Last command will install the plugin in your local repo (inside `.m2` directory) ... and that's all! Now you can use this version of the plugin. Just set `1.6.7-SNAPSHOT` as JavaPackager version in your POM.

> I'm using Java 11 because newer versions cause problems with Gradle 6 (yes! I have to upgrade Gradle, but it requires time as some plugins are no longer available in newer versions 😓)

**Comment by fvarrui** [comment] 2022-07-18 07:28
> Is it a normal requirement to install FUSE to execute AppImages?

Yes, are you testing on WSL? Because I got same error. I've tried on LinuxMint and it seems to be working fine. 🤷‍♂️ 

[Here](https://github.com/AppImage/AppImageKit/wiki/FUSE) you can find instructions and why AppImage uses FUSE.

**Comment by fvarrui** [comment] 2022-07-18 07:29
Branch issue-214 merged into devel.

**Comment by salmonb** [comment] 2022-07-18 07:48
> are you testing on WSL?

No, I'm on Ubuntu 22.04. FUSE is already installed but it's FUSE 3, and the AppImage requires FUSE 2. It's possible to install FUSE 2 beside FUSE 3, which I did, and then the AppImage is running :+1: 

Do you know if there could be an option to choose the FUSE version when generating the AppImage?

> Branch issue-214 merged into devel.

Great job :partying_face:

**Comment by fvarrui** [comment] 2022-07-18 10:10
JavaPackager v1.6.7 released to Maven Central. See changes [here](https://github.com/fvarrui/JavaPackager/releases/tag/v1.6.7).

**Closed by fvarrui** 2022-07-18 10:10 UTC
Labels: bug, fixed, feedback
