### ISSUE TITLE
A suitable of java could not be found on your system

### ISSUE THREAD

**Issue by xukai59740** [fvarrui/JavaPackager#150] opened 2022-02-22 04:41 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
`SetupError - A suitable of java could not be found on your system` when I run the application

**Steps to reproduce the issue/enhancement:**

1. [ Build the exe install file ]
2. [ Install success ]
3. [ run the application ]
3. [ get error dialog ]

**What is the expected behavior?**
it's normally worked

**What is the current behavior?**
can't find java runtime env when setup

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
    this is config:
 ```
    ..........
    version = Platform.windows
    platform = currentPlatform
    mainClass = setup.mainClassName
    bundleJre = true
    customizedJre = false
    generateInstaller = true
    vmArgs = ["-Dprism.maxvram=512m -XX:+UseG1GC"]
    runnableJar = file("$buildDir/libs/desktop-uber.jar")
    copyDependencies = true
    administratorRequired = false
   winConfig {
       generateSetup = true
       generateMsi = true
       disableDirPage = false
       disableProgramGroupPage = false
       disableFinishedPage = false
       disableWelcomePage = true
       exeCreationTool = WindowsExeCreationTool.winrun4j
   }
```
    
 this is build log:
   ```
Bundling JRE ... with D:\develop_env\openjdk-16.0.2_windows-x64_bin\jdk-16.0.2
        Creating customized JRE ...
        Getting required modules ... 
        Required modules found: [ALL-MODULE-PATH]
        
        Creating JRE with next modules included: ALL-MODULE-PATH
        Using D:\develop_env\openjdk-16.0.2_windows-x64_bin\jdk-16.0.2\jmods modules directory
        Executing command: cmd.exe /s /c "D:\develop_env\openjdk-16.0.2_windows-x64_bin\jdk-16.0.2\bin\jlink --module-path D:\develop_env\openjdk-16.0.2_windows-x64_bin\jdk-16.0.2\jmods --add-modules ALL-MODULE-PATH --output C:\Users\kk\IdeaProjects\demo\kotlin\desktop\build\MOST\jre --no-header-files --no-man-pages --strip-debug --compress=2"
        WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
        Removing folder [C:\Users\kk\IdeaProjects\demo\kotlin\desktop\build\MOST\jre\legal]
    JRE bundled in C:\Users\kk\IdeaProjects\demo\kotlin\desktop\build\MOST\jre!
    
```

**What is the motivation / use case for changing the behavior?**
Update version 1.5.1 to 1.6.3, switch to winrun4j from launch4j

**Please tell us about your environment:**

- JavaPackager version: 1.6.3
- OS version: Win10 x64
- JDK version: 16
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by xukai59740** [comment] 2022-02-23 03:40
this winrun4j/app.ini
```
main.class=WinRun4JLauncher
log.level=error
ini.override=true
classpath.1=libs\*.jar
vm.location=jre\bin\client\jvm.dll
working.directory=.
vmarg.1=-Dprism.order=d3d,sw -Dprism.maxvram=512m -XX:+UseG1GC

[ErrorMessages]
java.not.found=A suitable version of Java could not be found on your system. Please contact ACME.
java.failed=Java failed to startup successfully. Please contact ACME.
```

**Comment by fvarrui** [comment] 2022-02-24 00:23
I've been trying with a sample project using a similar plugin configuration, and it's working fine. I'm not able to reproduce your issue, sorry! 

The only thing I haven't tried yet is to use a FAT JAR.

**Comment by xukai59740** [comment] 2022-02-25 01:18
Thanks for checking,
So from the error log, the reason for this problem is that when running the exe application, JRE version not match.

**Comment by fvarrui** [comment] 2022-02-25 07:43
I'll keep investigating

**Comment by fvarrui** [comment] 2022-02-27 18:34
I've managed to reproduce issue upgrading from JDK11 to JDK17.

**Comment by fvarrui** [comment] 2022-02-27 18:59
The problem is that `vm.location` property in INI file is not pointing to the right DLL file.

I can see a difference in the generated JRE by `jlink` from one JDK version to another:

- **AdoptOpen JDK 11.0.1**: generates `jre\bin\client\jvm.dll` and `jre\bin\server\jvm.dll`.
- **Eclipse Adoptium JDK 17.0.1**: only generates `jre\bin\server\jvm.dll`.

As JavaPackager generates an INI file ponting to `jre\bin\client\jvm.dll` by default, running EXE file fails becasue it can find this DLL. Issue [159](https://github.com/fvarrui/JavaPackager/issues/159) clears up the problem.

Maybe a solution could be override this behaviour, including a new string property `winConfig.vmLocation`:

1. If `winConfig.vmLocation` is specified, checks if file exists before generating winrun4j INI file ... else, throws an exception.
2. If `winConfig.vmLocation` is not specified, first uses `jre\bin\client\jvm.dll` value by default, and checks if exists before generating winrun4j INI file ... else, tries step 3.
3. It uses `jre\bin\server\jvm.dll` value by default, and checks if exists before generating winrun4j INI file ... else, throws an exception.

**Comment by fvarrui** [comment] 2022-02-27 19:04
> this winrun4j/app.ini file when run Gradle packageMyApp
> 
> ```
> main.class=WinRun4JLauncher
> log.level=error
> ini.override=true
> classpath.1=libs\*.jar
> vm.location=jre\bin\client\jvm.dll
> working.directory=.
> vmarg.1=-Dprism.order=d3d,sw -Dprism.maxvram=512m -XX:+UseG1GC
> 
> [ErrorMessages]
> java.not.found=A suitable version of Java could not be found on your system. Please contact ACME.
> java.failed=Java failed to startup successfully. Please contact ACME.
> ```

You can check this changing `vm.location=jre\bin\client\jvm.dll` in INI file to `vm.location=jre\bin\server\jvm.dll` and then running your EXE.

**Comment by xukai59740** [comment] 2022-02-28 09:03
Cool, it's worked, I manually changed `client` to `server`.
Looks like we need a winConfig.vmLocation

**Comment by fvarrui** [comment] 2022-02-28 18:17
Changes published in branch [issue-150](https://github.com/fvarrui/JavaPackager/tree/issue-150) as JavaPackager 1.6.4-SNAPSHOT.

You can build and install this SNAPSHOT version following next steps:

```bash
git clone https://github.com/fvarrui/JavaPackager --branch issue-150
cd JavaPackager
gradlew publishToMavenLocal
```

Please, test it and give me some feedback!

**Comment by fvarrui** [comment] 2022-03-02 20:08
Branch issue-150 merged into devel. I'll release JavaPackager 1.6.4 to Maven Central asap

**Comment by fvarrui** [comment] 2022-03-03 09:05
JavaPackager 1.6.4 released to Maven Central.

**Closed by fvarrui** 2022-03-03 09:05 UTC
Labels: bug
