### ISSUE TITLE
Change default task manager processes name

### ISSUE THREAD

**Issue by NMNaufaldo** [fvarrui/JavaPackager#93] opened 2021-02-21 06:12 UTC
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
The task manager processes name not use the application name, instead use default Java platform name. In my case, the name is "OpenJDK Platform Binary"

**What is the expected behavior?**
Task manager process name should use the application name

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
Screenshot : [Task Manager Process Name](https://ibb.co/kmSHh4t)

**What is the motivation / use case for changing the behavior?**
Make a difference name between the software on task manager

**Please tell us about your environment:**

- JavaPackager version: 1.5.1
- OS version: Windows 10
- JDK version: 15
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment] 2021-02-21 08:45
Hi @NMNaufaldo!
Yes, you are right ... showing **OpenJDK Platform binary** on "Task Manager" is confusing for the final user. I didn't realize on this detail.

I'm using AdoptOpenJDK and it shows something like this:
![image](https://user-images.githubusercontent.com/4354486/108619427-b6389580-741c-11eb-834f-faa2ab578e93.png)

Reading [Launch4J docs](http://launch4j.sourceforge.net/docs.html), which is the tool used by JavaPackager to generate Windows binaries, I found the next:
![image](https://user-images.githubusercontent.com/4354486/108619487-1cbdb380-741d-11eb-9377-e100e0deeeab.png)
There's a possible solution allowing to use **jniGui32** option with JavaPackager, which has some disadvantages: e.g. it only works with 64 bit JDK/JRE. If you can confirm me that this option meets your needs, I'll add it to JavaPackager.

Another solution could be using [WinRun4J](http://winrun4j.sourceforge.net/) to generate Windows binaries, instead of Launch4J (or let the developer to choose which tool to use), as it seems to have solved this issue, but I'm not sure if the effort is worth it.

**Comment by NMNaufaldo** [comment] 2021-02-21 09:22
I think we must provide 2 options to generate windows binaries. The default option will use Launch4J. Because WinRun4J has a lot more features than Launch4J and I think will be easier to use WinRun4J with JavaPackager since WinRun4J requires the user to create a `*.ini` file to generate executable.

This feature is really important for production, we will really appreciate the effort :)

**Comment by fvarrui** [comment] 2021-02-21 10:14
Ok. But we must consider other factors, such as that Launch4j is cross-platform, so that it's possible to generate Windows binaries from GNU / Linux, for example. I'm not sure how to handle this with WinRun4J. Any help would be appreciated 😃

**Comment by fvarrui** [comment] 2021-03-16 20:18
Bad news! I've been trying to build a Windows EXE with **WinRun4j**, but I've run into a problem. When running my EXE, I've got this error message:

```xml
C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>HelloWorldMaven.exe

C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>[info] Module Name: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\HelloWorldMaven.exe
[info] Module INI: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\HelloWorldMaven.ini
[info] Module Dir: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\
[info] INI Dir: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\
[info] Configured vm.location: jre\bin\client\jvm.dll
[info] Found VM: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre\bin\client\jvm.dll
[info] Expanding Classpath: HelloWorldMaven.exe
[info] Generated Classpath: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\HelloWorldMaven.exe
[info] VM Args:
[info] vmarg.0=-Djava.class.path=C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\HelloWorldMaven.exe
[info] Registering natives for Native class
[warn] Could not find Native class
 [err] Could not find or initialize main class
java.lang.NoClassDefFoundError: IllegalName: io/github/fvarrui/helloworld/Main
        at java.base/java.lang.ClassLoader.preDefineClass(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at org.boris.winrun4j.classloader.EmbeddedClassLoader.findClass(EmbeddedClassLoader.java:98)
```

I tried to fix it, but I have not succeeded! 😞 

There's an [issue opened](https://github.com/poidasmith/winrun4j/issues/45) about this since 2013, but it seems that this project is not mainteined anymore.

Another possibility is to use [JSmooth](http://jsmooth.sourceforge.net/), but it also seems to be abandoned, as its latest release was in 2007.

Any suggestions?

**Comment by fvarrui** [comment] 2021-03-16 20:27
There's a [work around](https://github.com/poidasmith/winrun4j/issues/45#issuecomment-29283715) as explained in the link, but it is not elegant to force JavaPackager's users to put their main class outside of a package

**Comment by NMNaufaldo** [comment] 2021-03-17 16:55
I want to help but I have no idea sorry 😢

**Comment by fvarrui** [comment] 2021-03-21 15:07
Hi @NMNaufaldo!

I finally got it to work 🤯 and this feature is available in [issue-93](https://github.com/fvarrui/JavaPackager/tree/issue-93) branch.

There's a new property available to choose between **Launch4J** or **WinRun4J**:
```xml
<winConfig>
    <exeCreationTool>launch4j|winrun4j</exeCreationTool>
</winConfig>
```
It seems to be working as expected:
![image](https://user-images.githubusercontent.com/4354486/111909888-f2303c00-8a56-11eb-86bc-5da66365e8be.png)

Remember that you have to [install JavaPackager manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin) to your local repo.

Please, try it and give me some feedback!

**Comment by fvarrui** [comment] 2021-03-21 15:13
Oh! ... I was not able to merge INI file inside the executable, so INI file, which controls the EXE behaviour, has to be placed just next to the EXE. I think this could be a bit unsecure, as INI file could be changed although EXE file is signed 😮. I'd not recommend to use this option, unless you really know what are you doing.

**Comment by fvarrui** [comment] 2021-07-04 19:32
I close this issue because it has no activity. If you are interested in continuing with this, let me know and I'll reopen it.
Thanks!

**Comment by Thomy13** [comment] 2022-01-16 18:45
This feature would be great. It seems to be impossible for me to do with launch4j. Maybe #issue-93 could be merged?

**Comment by fvarrui** [comment] 2022-01-17 17:14
> This feature would be great. It seems to be impossible for me to do with launch4j. Maybe #93 could be merged?

Hi @Thomy13!
Ok, if you are interested in this feature, I could include issue-93 branch into the next release. But I has to be tested a bit more! Do you volunteer? 😅 ... asap as I'll merge it into devel branch, I could release it as a SNAPSHOT version, and then, you could test it.

**Comment by Thomy13** [comment] 2022-01-17 19:42
> > This feature would be great. It seems to be impossible for me to do with launch4j. Maybe #93 could be merged?
> 
> Hi @Thomy13! Ok, if you are interested in this feature, I could include issue-93 branch into the next release. But I has to be tested a bit more! Do you volunteer? 😅 ... asap as I'll merge it into devel branch, I could release it as a SNAPSHOT version, and then, you could test it.

Awesome! I can test this, yes. :D

**Comment by fvarrui** [comment] 2022-01-25 17:52
Branch [issue-93](https://github.com/fvarrui/JavaPackager/tree/issue-93) merged into [devel](https://github.com/fvarrui/JavaPackager/tree/devel).

**Comment by fvarrui** [comment] 2022-01-25 18:14
> Oh! ... I was not able to merge INI file inside the executable, so INI file, which controls the EXE behaviour, has to be placed just next to the EXE. I think this could be a bit unsecure, as INI file could be changed although EXE file is signed 😮. I'd not recommend to use this option, unless you really know what you are doing.

You can now test JavaPackager 1.6.3-SNAPSHOT. Remember that since it's a SNAPSHOT version, you must install it manually in your local repository. Follow the instructions in the [README](https://github.com/fvarrui/JavaPackager/blob/devel/README.md).

For now, JavaPackager only merges `exe.manifest` and ICO file with the EXE. But it would be great if we find out how to merge also the INI file inside it 🤔. Any help will be welcomed!

**Comment by fvarrui** [comment] 2022-02-11 10:54
JavaPackager v1.6.3 released to Maven Central.

It will be available in a while!

**Closed by fvarrui** 2022-02-11 10:54 UTC
Labels: enhancement

**Comment by FelipeAumannRS** [comment] 2022-05-31 11:44
Hello Guys
@fvarrui I was unable to reproduce what you achieved here [https://github.com/fvarrui/JavaPackager/issues/93#issuecomment-803599775](link)

What I have done:

1. added javaPackager dependency:
<dependency>
            <groupId>io.github.fvarrui</groupId>
            <artifactId>javapackager</artifactId>
            <version>1.6.6</version>
</dependency>

2. added plugin:
<plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.6</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            
                            <mainClass>${javafx.mainClass}</mainClass>
                            
                            <platform>windows</platform>
                            
                            <winConfig>launch4j|winrun4j</winConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

after trying to "mvn clean install", I get this error:
![image](https://user-images.githubusercontent.com/26864246/171165539-8732cd5e-e80e-4f51-9fbe-52f4362e6a78.png)

I already use Launch4J to package my application into an .exe (idk but this info might be useful, just in case).

Any ideas on that? Thanks

**Comment by fvarrui** [comment] 2022-05-31 19:15
Hi @FelipeAumannRS!

> 1. added javaPackager dependency:
> 
> ```
> <dependency>
>             <groupId>io.github.fvarrui</groupId>
>             <artifactId>javapackager</artifactId>
>             <version>1.6.6</version>
> </dependency>
> ```

You don't have to add JavaPackager as a dependency to your project, since it's only needed during the build process, not when your app is running.

You are using a model of the configuration, which is not completly valid. I mean, when you find "true|false", you should choose one option: `true` or `false`, but not both. Or when you see "..." (three dots), this means that there can be a lot more of properties/parameters. Here you can find some [examples](url).

Find fixed your plugin configuration:

```
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>1.6.6</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <mainClass>${javafx.mainClass}</mainClass>
                <bundleJre>true</bundleJre>
                <customizedJre>false</customizedJre>
                <generateInstaller>true</generateInstaller>
                <platform>windows</platform>
                <winConfig>
                    <exeCreationTool>winrun4j</exeCreationTool>
                </winConfig>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I guess that you are building a JavaFX application .... If so, take a look into this [issue](https://github.com/fvarrui/JavaPackager/issues/141#issuecomment-1020723653) to avoid problems.

**Comment by fvarrui** [comment] 2022-06-01 12:53
Hi @FelipeAumannRS!
The generated runnable JAR works fine ... the problem is that if you have a look into the MANIFEST.MF file inside it, you will see that all classpath entries points to `libs/`, so `libs/` has to be next to the runnable JAR ... but if you are using JavaPackager, why do you need to run your runnable JAR directly?

Just do a test: 
```bash
copy .\target\Nume-ALFA-0.2-runnable.jar .\target\Nume\
cd .\target\Nume
java -jar .\Nume-ALFA-0.2-runnable.jar
```
Give feedback, please!
