### ISSUE TITLE
Missing jarFile in macOS-app

### ISSUE THREAD

**Issue by nachsommer** [fvarrui/JavaPackager#1] opened 2019-05-09 09:33 UTC
When generating the Program.app the jarFile is not included, neither it is listed in the Info.plist nor is it copied to the lib folder. Therefore, the generated Program.app cannot run with macOS.

**Comment by fvarrui** [comment] 2019-05-09 13:39
Hi Heinrich, could you post here the output message of the maven command? README file of this repository is a bit out of date, sorry. Plugin's version is 0.4.0. I've been trying in a new setted up machine with Mac OS and I realized that, as you said, JAR file isn't been copied in target/app/Program.app/Contents/Resources/Java. I manually moved JAR file to this place and other jar libraries from "libs" to parent folder and Program.app works fine. Could you confirm me this, please? Thanks!

**Comment by fvarrui** [comment] 2019-05-09 15:01
I fixed some things and now runnable JAR file and JAR libraries are generated in the right place. Also, a symbolic link to /Applications folder is created in DMG file, so now it's easier to install the app. Version number has been increased to 0.5.0. You have to get JavaPackager changes and install the new version: `git pull && mvn install`, and upgrade JavaPackager maven plugin version in your project's POM file and run again `mvn package` to generate DMG file.

**Comment by fvarrui** [comment] 2019-05-09 15:17
Demo project available [here](https://github.com/dam-dad/HolaMundoMejorado).

**Comment by nachsommer** [comment] 2019-05-10 08:19
Thank you so much. It works now! The only thing, at least on my machine (macOS 10.14) is that the `startup` file in `Contents/MacOS` seems not to be signed. The effect is that the program can be launched in the command line by
`Program.app/Contents/MacOS/startup`
without problems. However, a double click on the icon comes with a requester saying: "JRELoadError". In the console, then, an error message is issued that the `startup` file is not codesigned. After codesigning with
`sudo codesign -f --deep -s - "Program.app/Contents/MacOS/startup"`
it still does not work. Do you have a suggestion how to resolve it? 
Thanks a lot for your help!

**Comment by fvarrui** [comment] 2019-05-10 08:57
I'm using macOS 10.12. Please, try to bundle JRE in the app, changing `bundleJre` configuration param to `true` in pom.xml. I only can reproduce JRELoadError this way, when bundleJre is false. I'm going to include your command to codesign `startup` just before generate DMG, but I'd like to know if after codesigning startup it doesn't throw an error message.

**Comment by nachsommer** [comment] 2019-05-10 09:38
Bundling on mojave 10.14 fails. It generates the following errors:

> [INFO] Create customized JRE ... with /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
> [info] Executing command: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/jdeps --print-module-deps --class-path /MyProgram/target/app/libs/* /MyProgram/target/MyProgram-4.5i.jar
> [info] Warning: split package: javax.xml.parsers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: javax.xml.transform jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: javax.xml.transform.dom jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: javax.xml.transform.sax jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: javax.xml.transform.stream jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jar
> [info] Warning: split package: org.w3c.dom.css jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom.events jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jar
> [info] Warning: split package: org.w3c.dom.html jrt:/jdk.xml.dom /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xercesImpl-2.11.0.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom.ranges jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom.stylesheets jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom.traversal jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.w3c.dom.views jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.xml.sax jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.xml.sax.ext jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] Warning: split package: org.xml.sax.helpers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar
> [info] java.base,java.desktop,java.prefs,java.scripting,java.sql,jdk.jsobject
> [info] Executing command: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/jlink --module-path /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/jmods --add-modules java.scripting,jdk.unsupported,Warning: split package: javax.xml.parsers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.dom jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.sax jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.stream jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jarWarning: split package: org.w3c.dom.css jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.events jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jarWarning: split package: org.w3c.dom.html jrt:/jdk.xml.dom /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xercesImpl-2.11.0.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.ranges jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.stylesheets jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.traversal jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.views jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax.ext jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax.helpers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarjava.base,java.desktop,java.prefs,java.scripting,java.sql,jdk.jsobject --output /MyProgram/target/app/jre --no-header-files --no-man-pages --strip-debug --compress=2
> [info] Error: Module Warning: split package: javax.xml.parsers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.dom jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.sax jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: javax.xml.transform.stream jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jarWarning: split package: org.w3c.dom.css jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.events jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jar /MyProgram/target/app/libs/batik-ext-1.9.1.jarWarning: split package: org.w3c.dom.html jrt:/jdk.xml.dom /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xercesImpl-2.11.0.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.ranges jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.stylesheets jrt:/jdk.xml.dom /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.traversal jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.w3c.dom.views jrt:/java.xml /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax.ext jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarWarning: split package: org.xml.sax.helpers jrt:/java.xml /MyProgram/target/app/libs/xmlParserAPIs-2.0.2.jar /MyProgram/target/app/libs/xml-apis-1.0.b2.jarjava.base not found
> [INFO] Creating Mac OS X app bundle...
> [INFO] -----> Creating and setting up the bundle directories
> [INFO] -----> Creating startup file
> [info] Copying stream to file [/MyProgram/target/app/Contents/MacOS/startup]
> [INFO] -----> Copying icon file to Resources folder
> [info] Copying file [assets/mac/MyProgram.icns] to folder [/MyProgram/target/app/Contents/Resources]
> [INFO] -----> Moving dependencies to Java folder
> [info] Moving folder content [/MyProgram/target/app/libs] to folder [/MyProgram/target/app/Contents/Resources/Java]
> [info] Moving file [/MyProgram/target/MyProgram-4.5i.jar] to folder [/MyProgram/target/app/Contents/Resources/Java]
> [INFO] -----> Bundling JRE
> [INFO] Moving the JRE Folder from : [/MyProgram/target/app/jre] to PlugIn folder: [/MyProgram/target/app/Contents/PlugIns/jre/Contents/Home]
> [info] Moving folder content [/MyProgram/target/app/jre] to folder [/MyProgram/target/app/Contents/PlugIns/jre/Contents/Home]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 19.732 s
> [INFO] Finished at: 2019-05-10T11:24:44+02:00
> [INFO] Final Memory: 80M/277M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal fvarrui.maven:javapackager:0.5.0:package (default) on project MyProgram: Source folder /MyProgram/target/app/jre is not a directory -> [Help 1]`

Please not that I've added explicit paths into PackageMojo.java because otherwise it got confused with different JDKs, and the jlink program was not found, therefore I've modified to 

~~~~
private void createCustomizedJre() throws MojoExecutionException {
		if (!bundleJre) return;
		
		getLog().info("Create customized JRE ... with "+System.getProperty("java.home"));
		
		File libsFolder = new File(appFolder, "libs");
		File jreFolder = new File(appFolder, "jre");
		
		// determine required modules for libs and app jar
		String modules = "java.scripting,jdk.unsupported,"; // add required modules by default
		modules += ProcessUtils.execute(System.getProperty("java.home")+"/bin/jdeps", "--print-module-deps", "--class-path", new File(libsFolder, "*"), jarFile);
		
		// if exists, remove old jre folder
		if (jreFolder.exists()) jreFolder.delete();

		// generate customized jre using modules
		File modulesDir = new File(System.getProperty("java.home"), "jmods");
		ProcessUtils.execute(System.getProperty("java.home")+"/bin/jlink", "--module-path", modulesDir, "--add-modules", modules, "--output", jreFolder, "--no-header-files", "--no-man-pages", "--strip-debug", "--compress=2");
		
	}
~~~~

**Comment by fvarrui** [comment] 2019-05-10 10:21
Ok, error occurs because it can't find `jre` folder, because JRE generation fails, because `jlink` execution fails 😅 ... I think it's so. I included your changes, so now we are sure that it'll find the right `jlink` command (the one that corresponds to the same JDK that maven is using). Sorry, but I'm not a proficient Mac user. Is it working with your changes?

**Comment by nachsommer** [comment] 2019-05-10 22:24
Not really. The construction of the JRE bundle wasn't correct, since the call with `jlink` got confused with the extra modules. After I've changed the code to
~~~~
        // determine required modules for libs and app jar
        String modules = "java.scripting,jdk.unsupported,"; // add required modules by default
        // modules += ProcessUtils.execute(System.getProperty("java.home") + "/bin/jdeps", "--print-module-deps", "--class-path", new File(libsFolder, "*"), jarFile);
~~~~
i.e. commented the line with the extra dependencies, at least the build was successful. However, though the maven build went through without errors and the Program.app was perfectly generated, a start by double clicking did: nothing. Even no error message, neither with a requester saying "JRELoadError" nor on the console where also no message was issued. Needless to say that a direct call via terminal, i.e.
`Program.app/Contents/MacOS/startup` starts the app correctly and without any complaints. Can you reproduce this strange behaviour? And do you have a clue how to start the app by clicking? Thanks a lot for your help!

**Comment by nachsommer** [comment] 2019-05-11 09:08
We're approaching the solution: The problem was that my Program.app includes modules which are not correctly analyzed by `jdeps` prior to Java12 (to be specific: the javafx.media package, see [here]( https://bugs.openjdk.java.net/browse/JDK-8211887)). Only with Java 12.0 and the additional options -q --ignore-missing-deps `jdeps` runs correctly (skipping the split package-warning). 
~~~~
        // determine required modules for libs and app jar
        String modules = "java.scripting,jdk.unsupported,"; // add required modules by default
        modules += ProcessUtils.execute(System.getProperty("java.home") + "/bin/jdeps", "-q", "--ignore-missing-deps", "--print-module-deps", "--class-path", new File(libsFolder, "*"), jarFile);
~~~~
After including these options, the build runs successfully. However, the double clicking option still refuses to start, even after codesigning the package. Codesigning itsself does not complete because the structure of the Program.app does not comply with the structure required by Apple. Could you rearrange the structure of the Contents according to this scheme:

<img width="715" alt="_correctAppBundleStructure" src="https://user-images.githubusercontent.com/39944073/57567638-94535780-73dc-11e9-8f94-e119cd1ac1c9.png">

The directory `_CodeSignature` is added by `codesign`, however, I'm not sure whether the `startup` bin needs the structure you've provided or whether it goes for the official Apple layout as well. Can you say something about the `startup` bin? How is it build? Do you have a source code for that? How to build this stub?
I think after adopting the launcher/startup bin the package should compile fine with Java12 and codesigning – even without the JRE embeded.
Thanks a lot for your help...

**Comment by nachsommer** [comment] 2019-05-11 14:20
The problem is solved. I've managed to start the whole bundle without the binary stub, thanks to your VelocityUtils already implemented. Also, the option with/without JRE embeded works now fine. If you grant me access I could upload a commit. – There was no need anymore to change the bundle structure or to codesign something.

**Comment by fvarrui** [comment] 2019-05-11 20:29
Great job!! Thanks a lot! I sent to you an invitation to collaborate in the project. When you commit your changes I’ll try them on Windows and GNU/Linux.

**Comment by fvarrui** [comment] 2019-05-14 10:08
I'm going to close this issue if it's already solved. I refactored the project and did that if JDK version is < 13 then generate a full JRE (not optimized), but it doesn't prevent to embed a JRE in the app. I also included default icons for all platforms and now it's able  to require administrator privileges if it's needed on macOS. Thank you so much for you help!

**Closed by fvarrui** 2019-05-14 10:08 UTC
