### ISSUE TITLE
Version 1.6.0 can't run with gralde 5.4.1

### ISSUE THREAD

**Issue by hectorqin** [fvarrui/JavaPackager#127] opened 2021-09-22 07:13 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

gradle build error

**Steps to reproduce the issue/enhancement:**

1. Upgrade this plugin from 1.5.1 to 1.6.0
2. Run `JAVAFX_PLATFORM=win ./gradlew packageReaderWin`

**What is the expected behavior?**

Build success

**What is the current behavior?**

Build error

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

```log 
> Task :packageReaderWin FAILED
Using packager io.github.fvarrui.javapackager.packagers.WindowsPackager

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageReaderWin'.
> 'org.gradle.jvm.toolchain.JavaToolchainSpec org.gradle.api.plugins.JavaPluginExtension.getToolchain()'
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.6.0
- OS version: MacOS 11.2.3
- JDK version:  11
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 5.4.1

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment] 2021-09-22 14:32
Hi @hectorqin!
I've managed to reproduce your issue.

This problem is related to a new property added since v1.6.0: `packagingJdk`, so now JavaPackager [invokes an specific Gradle method](https://github.com/fvarrui/JavaPackager/blob/07510e8ba4add04b1880563856acbe73c98cc08b/src/main/java/io/github/fvarrui/javapackager/gradle/GradleContext.java#L97) which is not available for Gradle 5.4.1. I'll try to fix it asap.

https://github.com/fvarrui/JavaPackager/blob/07510e8ba4add04b1880563856acbe73c98cc08b/src/main/java/io/github/fvarrui/javapackager/gradle/GradleContext.java#L95-L107

You can follow the work in progress in [issue-127 branch](https://github.com/fvarrui/JavaPackager/tree/issue-127).

Thanks!

**Comment by fvarrui** [comment] 2021-09-22 23:59
Fixed in v1.6.1-SNAPSHOT (branch issue-127). 

If it works fine for you, I'll release v1.6.1 to Maven Central.

**Comment by hectorqin** [comment] 2021-09-23 01:42
It works fine, thank you!

**Comment by fvarrui** [comment] 2021-09-23 11:34
Branch issue-127 merged into master

**Comment by fvarrui** [comment] 2021-09-23 11:49
JavaPackager v1.6.1 just released to Maven Central. It will take a few hours to be available to download.

**Closed by fvarrui** 2021-09-23 11:49 UTC
Labels: bug
