### ISSUE TITLE
Execution failed for task, `copyInputStreamToFile`

### ISSUE THREAD

**Issue by Borewit** [fvarrui/JavaPackager#139] opened 2022-01-05 19:02 UTC
**Issue**

I try to create a Windows installer using JavaPacker.
Tried all kinds of options, but I keep getting the following error:

After 
```
> Task :packageMyApp FAILED
        Using packager io.github.fvarrui.javapackager.packagers.WindowsPackager
        Creating app ...
            Initializing packager ...
                PackagerSettings [outputDirectory=C:\Users\Borewit\code\github\listFix\build, licenseFile=C:\Users\Borewit\code\github\listFix\LICENSE.txt, iconFile=null, generateInstaller=true, mainClass=listfix.view.GUIScreen, name=listFix, displayName=listFix, version=2.3.0, description=listFix, url=null, administratorRequired=false, organizationName=ACME, organizationUrl=, organizationEmail=, bundleJre=true, customizedJre=true, jrePath=null, jdkPath=C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot, additionalResources=[], modules=[], additionalModules=[], platform=windows, envPath=null, vmArgs=[], runnableJar=C:\Users\Borewit\code\github\listFix\build\libs\listFix-2.3.0-all.jar, copyDependencies=false, jreDirectoryName=jre, winConfig=WindowsConfig [icoFile=null, headerType=gui, companyName=ACME, copyright=ACME, fileDescription=listFix, fileVersion=1.0.0.0, internalName=listFix, language=null, originalFilename=listFix.exe, productName=listFix, productVersion=1.0.0.0, trademarks=null, txtFileVersion=2.3.0, txtProductVersion=2.3.0, disableDirPage=true, disableProgramGroupPage=true, disableFinishedPage=true, disableRunAfterInstall=true, createDesktopIconTask=true, generateSetup=true, generateMsi=true, generateMsm=false, msiUpgradeCode=5e13fa80-4c85-4098-a459-6e944c3d5c1e, wrapJar=true, setupLanguages={english=compiler:Default.isl, spanish=compiler:Languages\Spanish.isl}, setupMode=installForAllUsers, signing=null, registry=Registry [entries=[]]], linuxConfig=null, macConfig=null, createTarball=false, createZipball=false, extra={}, useResourcesAsWorkingDir=true, assetsDir=C:\Users\Borewit\code\github\listFix\assets, classpath=null, jreMinVersion=null, manifest=Manifest [additionalEntries={}, sections=[]], additionalModulePaths=[], fileAssociations=null, packagingJdk=C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot, scripts=Scripts [bootstrap=null, preInstall=null, postInstall=null]]
            Packager initialized!
            
            Creating app structure ...
                App folder created: C:\Users\Borewit\code\github\listFix\build\listFix
                Assets folder created: C:\Users\Borewit\code\github\listFix\build\assets
            App structure created!
            
            Resolving resources ...
                License file found: C:\Users\Borewit\code\github\listFix\LICENSE.txt
                Copying resource [/windows/default-icon.ico] to file [C:\Users\Borewit\code\github\listFix\build\assets\listFix.ico]
```
I fails:
```
Execution failed for task ':packageMyApp'.
> 'void org.apache.commons.io.FileUtils.copyInputStreamToFile(java.io.InputStream, java.io.File)'
```

Do you have any a suggestion how to fix that?

As soon as I listed `io.github.fvarrui:javapackager:1.6.2` as a build script dependency, I got issues my `launch4j` task, as if something is interfering.

**Environment:**

- JavaPackager version: 1.6.2
- OS version: Windows
- JDK version:  17.0.1.12 ([Eclipse Adoptium, Temurin](https://adoptium.net/))
- Build tool: Gradle 

**Other information**
Code: https://github.com/Borewit/listFix/tree/javapackager

**Comment by Borewit** [comment] 2022-01-05 19:19
Maybe I should also say that my aim have gradle task which turns [lisFix()](https://github.com/Borewit/listfix), a Java desktop application, into a Windows installer `.msi` or `.exe`, with preferably a compiled in JRE.

Just to make it easy as possible for end-users to grab to application and start using it.

**Comment by fvarrui** [comment] 2022-01-06 13:36
Hi @Borewit!
I've been trying your project and manage to reproduce and "fix" your issue changing a bit your `build.gradle` (see below).

> ```
> Execution failed for task ':packageMyApp'.
> > 'void org.apache.commons.io.FileUtils.copyInputStreamToFile(java.io.InputStream, java.io.File)'
> ```

I think this problem is caused by this plugin (`com.gitlab.svg2ico:0.11`). If you comment the config related to this plugin, process continues. As far as I could find out, there's a conflict with `commons-io` dependency. I'll do some more research about this.

After this work around, there's another issue related with `jdeps`, as it seems that it doesn't like classes in the top-level directory:

```
Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\bin\jdeps" -q --multi-release 15 --ignore-missing-deps --print-module-deps C:\Users\fvarrui\GitHub\listFix\build\libs\listFix-2.3.0-all.jar"
Exception in thread "main" java.lang.module.FindException: Error reading module: C:\Users\fvarrui\GitHub\listFix\build\libs\listFix-2.3.0-all.jar
    at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:350)
    at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:237)
    at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
    at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:166)
    at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:521)
    at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
    at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
    at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
    at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: java.lang.module.InvalidModuleDescriptorException: JColorComboBoxTest.class found in top-level directory (unnamed package not allowed in module)
    at java.base/jdk.internal.module.ModulePath.toPackageName(ModulePath.java:720)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:555)
    at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at java.base/jdk.internal.module.ModulePath.jarPackages(ModulePath.java:621)
    at java.base/jdk.internal.module.ModulePath.lambda$readJar$6(ModulePath.java:653)
    at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:302)
    at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:129)
    at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:652)
    at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:331)
    ... 8 more
```

I fixed it by skipping `jdeps` call using `customizedJre=false` property, but this generates a full JRE.

> I just realized that you are using Java 17, and I tried with 15 ... I'm not sure this can cause any problems too.

Modified `build.gradle`:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'io.github.fvarrui:javapackager:1.6.2'
	}
}

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'java'
    id 'idea'
    id 'edu.sc.seis.launch4j' version '2.5.1'

    /* https://github.com/openjfx/javafx-gradle-plugin */
    id 'org.openjfx.javafxplugin' version '0.0.10'

    /* https://gitlab.com/svg2ico/svg2ico-gradle-plugin */
    //id "com.gitlab.svg2ico" version "0.11"

    /* Generate Java code from XSD */
    id 'org.unbroken-dome.xjc' version '2.0.0'

    id 'checkstyle'
}

apply plugin: 'edu.sc.seis.launch4j'
apply plugin: 'io.github.fvarrui.javapackager.plugin'

version '2.3.0'

sourceCompatibility = 8
targetCompatibility = 15

javafx {
    version = '17.0.1'
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics', 'javafx.swing']
    configuration = 'implementation'
}

project.mainClassName = 'listfix.view.GUIScreen'

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation 'junit:junit:4.13.2'

    implementation files('src/lib/net.mariottini.swing.jar')

    // Provides christophedelory.playlist.*
    implementation files('src/lib/lizzy.jar')

    implementation files('src/lib/jide-common.jar')
    implementation files('src/lib/jide-components.jar')

    // https://mvnrepository.com/artifact/com.jgoodies/jgoodies-common
    implementation 'com.jgoodies:jgoodies-common:1.8.0'

    // https://mvnrepository.com/artifact/com.jgoodies/jgoodies-looks
    implementation 'com.jgoodies:jgoodies-looks:2.7.0'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:30.1.1-jre'

    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    implementation 'javax.xml.bind:jaxb-api:2.3.1'

    // https://mvnrepository.com/artifact/log4j/log4j
    implementation 'log4j:log4j:1.2.6'

    // https://mvnrepository.com/artifact/commons-io/commons-io
    implementation 'commons-io:commons-io:2.11.0'
}

application {
    // Define the main class for the application.
    mainClass = project.mainClassName
}

sourceSets {
    main {
            java {
                srcDirs = ['src/main/java', 'build/generated/sources/xjc/java/main']
            }
            resources {
            	  srcDirs= ['src/main/resources']
    				}
        }
}

tasks.withType(JavaCompile) {
    compileTask -> compileTask.dependsOn xjcGenerate
}

task fatJar(type: Jar) {
    manifest {
        attributes 'Main-Class': project.mainClassName
    }
    setDuplicatesStrategy(DuplicatesStrategy.WARN)
    baseName = "listFix"
    archiveClassifier = "all"
    from { configurations.compileClasspath.filter{ it.exists() }.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

/*
tasks.register('makePngIcon', Svg2PngTask) {
    source = new File('src/main/svg/listFix() icon.svg')
    width = 64
	  height = 64
		destination = new File('src/main/resources/images/icon.png')
}

tasks.register('makeIcon', Svg2IcoTask) {
    input {
      source = new File('src/main/svg/listFix() icon.svg')
    }
	  destination = new File('website/favicon.ico')
}
*/

tasks.withType(Checkstyle) {
    exclude 'listfix/model/playlists/winamp/generated/**.java'
}

// https://github.com/TheBoegl/gradle-launch4j
/*
// Task commented due to: Could not set unknown property 'jarTask' for extension 'launch4j' of type edu.sc.seis.launch4j.Launch4jPluginExtension.
launch4j {
    headerType='gui'
    icon = "${projectDir}/website/favicon.ico"
    mainClassName = project.mainClassName
    companyName = 'Borewit'
    downloadUrl = 'https://github.com/Borewit/listFix/releases'
    fileDescription = 'Repairs Missing Entries in Playlist Files'
    supportUrl = 'https://github.com/Borewit/listFix/issues'
    copyConfigurable = [] // Don't copy dependencies
    jarTask = project.tasks.fatJar // Use fat jar
}
*/

task packageMyApp(type: io.github.fvarrui.javapackager.gradle.PackageTask, dependsOn: fatJar) {
	// mandatory
	mainClass = 'listfix.view.GUIScreen'
	runnableJar = file("build/libs/${project.name}-${project.version}-all.jar")
	// optional
	bundleJre = true
	generateInstaller = true
	administratorRequired = false
	platform = 'windows'
	licenseFile = file('LICENSE.txt')
	copyDependencies = false
	customizedJre = false
}

applicationDefaultJvmArgs = ['--add-exports=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED',
                             '--add-exports=java.desktop/sun.awt.shell=ALL-UNNAMED'
                            ]
```

**Comment by Borewit** [comment] 2022-01-06 16:35
Thank you so much for your help @fvarrui!

I switched to Oracle SDK 15 & used your modified `build.gradle`, seems to get a lot further, yet the following command runs into an error:

```
C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\crt2.o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\head\guihead.o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\head\head.o C:\Users\Borewit\AppData\Local\Temp\launch4j3361619180845378903o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingw32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingwex.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libgcc.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmsvcrt.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmoldname.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libkernel32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libuser32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libadvapi32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libshell32.a -o C:\Users\Borewit\code\github\listFix\build\launch4j\app.exe
```
which gives the following error:
```
C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\AppData\Local\Temp\launch4j3361619180845378903o: No such file or directory
C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingwex.a: No such file or directory
C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmoldname.a: No such file or directory
```

**Comment by fvarrui** [comment] 2022-01-06 23:02
> I switched to Oracle SDK 15 & used your modified `build.gradle`, seems to get a lot further, yet the following command runs into an error:
> 
> ```
> C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\crt2.o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\head\guihead.o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\head\head.o C:\Users\Borewit\AppData\Local\Temp\launch4j3361619180845378903o C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingw32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingwex.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libgcc.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmsvcrt.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmoldname.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libkernel32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libuser32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libadvapi32.a C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libshell32.a -o C:\Users\Borewit\code\github\listFix\build\launch4j\app.exe
> ```
> 
> which gives the following error:
> 
> ```
> C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\AppData\Local\Temp\launch4j3361619180845378903o: No such file or directory
> C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmingwex.a: No such file or directory
> C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\bin\ld.exe: cannot find C:\Users\Borewit\code\github\listFix\build\tmp\launch4j\bin-launch4j-3.12\w32api\libmoldname.a: No such file or directory
> ```

This issue is caused because the `gradle-launch4j` plugin is included twice (once explicitly in `build.gradle` and once implicitly by **javapackager**). I've merged your `launch4j` configuration to javapackager config, so there's no need to use gradle-launch4j.

Please, take a look to the PR (now it also generates and use your `website/favicon.ico` when packaging).

**Closed** 2022-01-07 16:37 UTC
