### ISSUE TITLE
Could not remove legal directory. Only on mac and linux?

### ISSUE THREAD

**Issue by Osiris-Team** [fvarrui/JavaPackager#328] opened 2023-05-20 12:24 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
When trying to package on mac: `Caused by: java.io.IOException: Unable to delete directory /Users/runner/work/Desku-Gradle-Starter-App/Desku-Gradle-Starter-App/desktop/build/desktop/desktop.app/Contents/PlugIns/jre.jre/Contents/Home/legal.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1127)
	at io.github.fvarrui.javapackager.utils.FileUtils.removeFolder(FileUtils.java:247)
	... 121 more`
Full build log: https://github.com/Osiris-Team/Desku-Gradle-Starter-App/actions/runs/5032033612/jobs/9025447503

When trying to package on linux/ubuntu: `Caused by: java.io.IOException: Unable to delete directory /home/runner/work/Desku-Gradle-Starter-App/Desku-Gradle-Starter-App/desktop/build/desktop/jre/legal.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1127)
	at io.github.fvarrui.javapackager.utils.FileUtils.removeFolder(FileUtils.java:247)
	... 149 more.`
Full build log: https://github.com/Osiris-Team/Desku-Gradle-Starter-App/actions/runs/5032033612/jobs/9025447469

It's a multi-module project: https://github.com/Osiris-Team/Desku-Gradle-Starter-App

**Steps to reproduce the issue/enhancement:**

release.yml contains the commands executed for each platform: https://github.com/Osiris-Team/Desku-Gradle-Starter-App/blob/master/.github/workflows/release.yml

Relevant build.gradle file: https://github.com/Osiris-Team/Desku-Gradle-Starter-App/blob/master/desktop/build.gradle
Note that on windows that build.gradle file works without issues.

**Comment by fvarrui** [comment] 2023-05-25 08:08
Hi @Osiris-Team!
Ok, the problem is here (line 247):

https://github.com/fvarrui/JavaPackager/blob/fa1ca46f66cb341b89c5a17808bb7e239e3269e7/src/main/java/io/github/fvarrui/javapackager/utils/FileUtils.java#L244-L251

I'm not really sure why `org.apache.commons.io.FileUtils.deleteDirectory` is failing, but it usually does when it hasn't permissions or any file is locked by another process.

Maybe we can try removing folders on Linux and Mac OS using the native command `rm`:

```java
public static void removeFolder(File folder) throws Exception {
    Logger.info("Removing folder [" + folder + "]");		
    try {			
        if (Platform.windows.isCurrentPlatform())
            deleteDirectory(folder);
        else {
            CommandUtils.execute("rm", "-fr", folder);
        }
    } catch (IOException e) {
        throw new Exception("Could not remove folder " + folder, e);
    }
}
```

I'll apply this patch and publish a snapshot version ASAP so you can test it.

**Comment by Osiris-Team** [comment] 2023-05-25 08:14
@fvarrui I think I had a similar issue in another project. What I did was to create a for loop that retries to delete the file like 1000 times or so and only then throw an exception. That worked since the files seemed to be locked only for a short time.

**Comment by fvarrui** [comment] 2023-05-25 23:58
Work in progress in branch `issue-328`

**Comment by fvarrui** [comment] 2023-05-26 00:01
Changes published as snapshot version `1.7.3-20230525.235840-4`.

Please, test it and give some feedback.

**Comment by fvarrui** [comment] 2023-05-26 00:03
> @fvarrui I think I had a similar issue in another project. What I did was to create a for loop that retries to delete the file like 1000 times or so and only then throw an exception. That worked since the files seemed to be locked only for a short time.

If this patch doesn't work, I'll try your approach

**Comment by Osiris-Team** [comment] 2023-05-26 08:36
Yes that fixed it! Beautiful, thanks!
https://github.com/Osiris-Team/Desku-Gradle-Starter-App/releases/tag/2.0.14

**Comment by fvarrui** [comment] 2023-06-06 10:51
I'm going to keep this issue open until this patch is released

**Comment by fvarrui** [comment] 2023-06-06 10:53
Branch `issue-328` merged into `devel` and removed, ready to be deployed.

**Comment by fvarrui** [comment] 2023-08-11 15:00
1.7.3 released to Maven Central

**Closed by fvarrui** 2023-08-11 15:00 UTC
Labels: bug, fixed, merged
