### ISSUE TITLE
How do I read from additionalResources?

### ISSUE THREAD

**Issue by chrisbakker** [fvarrui/JavaPackager#29] opened 2020-04-23 21:23 UTC
I'm really enjoying this utility. I have some extra resources that I've embedded into my Mac app but I can't figure out how to read them. I wrote some code to tell me what java thinks its root directory and it seems to be set to "/" and not anywhere within the blah.app directory. How do I get my root path set correctly so I can read from my resources directory.

Thanks.

**Comment by fvarrui** [comment] 2020-04-24 00:07
Hi @chrisbakker,
you are right, it's taking "/" as root directory. It was caused by the way `startup` script runs the jar file. Sorry for the inconveniences, but I didn't realize about that situation. You are the first one ;-D

I've fixed in 0.9.7-SNAPSHOT and I'll publish on Maven Central asap, so now your paths will be relative to your app `Resources` folder, where additional resources are being copied.

For example, if your app is in /Applications/blah.app, and in your code you use:
```java
File resource = new File("hello.txt");
```
Now, `resource` object will point to `/Applications/blah.app/Contents/Resources/hello.txt`, so you don't have to worry about your app location because it's relative.

Thanks for you comments and for using JavaPackager!

**Comment by chrisbakker** [comment] 2020-04-24 00:11
I really appreciate the quick response! This is exactly what I needed.

Thanks!

**Comment by fvarrui** [comment] 2020-04-24 00:16
It was easy to solve:
```bash
#!/bin/sh
# Mac OS X startup script generated by JavaPackager Maven Plugin
SCRIPTPATH=`cd "$(dirname "$0")" ; pwd`
#if($info.bundleJre)
JAVA=$SCRIPTPATH/../PlugIns/${info.jreDirectoryName}/Contents/Home/bin/java
#else
JAVA=`/usr/libexec/java_home`/bin/java
#end
BINARY=Java/${info.jarFile}
#if($info.envPath)
export PATH=${info.envPath}
#end
cd $SCRIPTPATH/../Resources       <------------- I've only added this line to script template
#if($info.administratorRequired)
/usr/bin/osascript -e "do shell script \"$JAVA ${info.vmArgs} -Dapple.laf.useScreenMenuBar=true -Xdock:name='${info.displayName}' -Xdock:icon=$SCRIPTPATH/../Resources/${info.name}.icns -jar $BINARY $@\" with administrator privileges"
#else
$JAVA ${info.vmArgs} -Dapple.laf.useScreenMenuBar=true -Xdock:name="${info.displayName}" -Xdock:icon=$SCRIPTPATH/../Resources/${info.name}.icns -jar $BINARY $@
#end
```
Please, when you try 0.9.7, tell me if it's fine!

**Comment by fvarrui** [comment] 2020-04-24 00:18
v0.9.7 will appear published on Maven Central in a few hours!

**Comment by chrisbakker** [comment] 2020-04-24 01:33
I just verified that my root directory now points to blah.app/Contents/Resources/.

Rock on! :)

**Comment by fvarrui** [comment] 2020-04-24 01:45
Cool!

**Closed by fvarrui** 2020-04-24 01:45 UTC
