### ISSUE TITLE
0.9.0 mac problems

### ISSUE THREAD

**Issue by mristuccia** [fvarrui/JavaPackager#19] opened 2020-03-08 13:52 UTC
Hi Fran,

I have problem with the new 0.9.0 version. The app does not start under macOS.

By manually launching the startup script I get this:

`marco$ ./phPatcher.app/Contents/MacOS/startup`
`-bash: ./phPatcher.app/Contents/MacOS/startup: /bin/sh^M: bad interpreter: No such file or directory`

I think there is the newline problem again. :)

Best,
marco

**Comment by fvarrui** [comment] 2020-03-08 15:02
Hi Marco,
You are right, that was the problem. I fixed and tried on MacOS and it seems to work fine now. Sorry for reintroduce the problem; it's caused by my IDE's configuration.

Please, could you give a try to JavaPackager 0.9.1-SNAPSHOT. It's not still available on Maven Central, so you have to install manually in your local repo following next steps:

```bash
git clone https://github.com/fvarrui/JavaPackager
cd JavaPackager
mvn install
```
Then, change JavaPackager version on your project's `pom.xml` file to 0.9.1-SNAPSHOT and

```bash
mvn clean package
```

**Comment by mristuccia** [comment] 2020-03-08 20:18
Hi Fran,

I've tested the 0.9.1-SNAPSHOT and can confirm that it works smoothly.
Thank you for your fast support as usual!

Best,
marco

**Comment by fvarrui** [comment] 2020-03-08 20:24
I’ll publish 0.9.1 on Maven Central ASAP. Thanks to you!

**Comment by mristuccia** [comment] 2020-03-09 12:29
Hi Fran,

unfortunately in the official 0.9.1 there is still the issue/regression.
The local 0.9.1-SNAPSHOT works without problem.

Best,
marco

**Comment by fvarrui** [comment] 2020-03-09 12:39
There must be something wrong during the publishing process. I’ll research about it. Please, use 0.9.1-SNAPSHOT till I can find where the bug is. Sorry for the inconveniences

**Comment by fvarrui** [comment] 2020-03-09 13:12
Maybe related to this issue on Windows: [Maven release plugin and Windows line breaks](https://stackoverflow.com/questions/11868590/maven-release-plugin-and-windows-line-breaks)

**Comment by fvarrui** [comment] 2020-03-10 11:18
Hi Marco,
I hope v0.9.3 solves your problem. I've tried on MacOS directly from Maven Central and `startup` endlines are LF characters. 

Please, tell me if we can close this issue.

Thanks!

**Comment by mristuccia** [comment] 2020-03-10 16:58
Hi Fran,

I can confirm that the v0.9.3 solves the problem.
Thank you as usual.

Best!

**Closed** 2020-03-10 17:06 UTC
