### ISSUE TITLE
Error at start on Windows

### ISSUE THREAD

**Issue by HumanG33k** [fvarrui/JavaPackager#41] opened 2020-07-08 14:36 UTC
Hello, 

I probably miss something but when i try to execute my generate exe it not start. 
After i start it in a powershell shell it says it can’t find my main class but the fat jar build start without trouble with a :
```bash
java -jar mydot.jar
```
This is my relevant pom part :
```xml
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.1.0</version>
                <executions>
                    <execution>
                        <id>windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            
                            <mainClass>com.mytestcompany.mytestproject.Main</mainClass>
                            
                            <bundleJre>false</bundleJre>
                            <runnableJar>target/mydot.jar</runnableJar>
                            <copyDependencies>false</copyDependencies>
                            <generateInstaller>true</generateInstaller>        
                            <administratorRequired>true</administratorRequired>
                            
                            <platform>windows</platform>
                            <winConfig>
                                <generateSetup>true</generateSetup>
                                <generateMsi>true</generateMsi>
                                <headerType>console</headerType>
                            </winConfig>
                    </configuration>
                    </execution>
               </executions>
           </plugin>
```
For the record my main javafx class is already in a wrapper java main class.

**Comment by fvarrui** [comment] 2020-07-08 14:51
Hi @HumanG33k!
Can you share `mvn package`, `mvn -v` and exe output,  please?

**Comment by fvarrui** [comment] 2020-07-08 23:11
Hi again!
Here you can find a sample project using a runnable fat jar, using same plugin options as yours.
https://github.com/fvarrui/HelloWorld

**Comment by HumanG33k** [comment] 2020-07-09 00:30
hi,
sry for waiting and thx to check my issue and try to help.
build is quite long + i try to  do anomymisation on files.
Has you will see its not a small project. I already read example and some already closed issues.  I probably miss somethings. 
[version.log](https://github.com/fvarrui/JavaPackager/files/4893837/version.log)
[package.log](https://github.com/fvarrui/JavaPackager/files/4893838/package.log)

I m aware about the fact 13 is already dead. (F*cking stupid 6 months release  )

**Comment by fvarrui** [comment] 2020-07-09 00:59
Ok! It seems that you are executing the plugin múltiple times, but If I’m not wrong, each execution removes the previous generated app. I know this is not the problem, but I have to warn you. Take a look at this [link](https://github.com/fvarrui/JavaPackager/blob/master/docs/plugin-configuration-samples.md#multiple-executions)!

Can you confirm to me that `com.wildturtles.mavenproject3.Main` is your main class? (Sorry, but I have to ask you)

Don’t worry about 13, I’m using too!! I’m too lazy to update it

**Comment by HumanG33k** [comment] 2020-07-09 02:10
yes it is. i miss it during my anonymisation. can you edit your post to remove it ? thx.
I absolutly not understand why its working in allinone jar when i run it in netbeans i have to specify the main class paht as arg :
```bash
-classpath %classpath com.organisation.mavenproject3.Main
```

**Comment by HumanG33k** [comment] 2020-07-09 03:22
do you know if something similar is possible with javapacker ?

**Comment by fvarrui** [comment] 2020-07-09 09:22
You can specify VM arguments to javapackager using `vmArgs` option.

I’ve seen that launch4j fails with too fat jars. Can you try your jar with launch4j in standalone mode?

**Comment by HumanG33k** [comment] 2020-07-09 16:08
For launch4j : 

The standalone launch4j says it need 1.6 -1.8  jre.
So i had the java 8 (install it) because i only have the openjdk 13 install.
I do it works (l4j starts)

I try to build the exe and this configuration file permit to start it : 
```xml 

<?xml version="1.0" encoding="UTF-8"?>
<launch4jConfig>
  <dontWrapJar>true</dontWrapJar>
  <headerType>gui</headerType>
  <jar>project-1.0-SNAPSHOT.jar</jar>
  <outfile>D:\USER\Projects\USER_tmp\Project\target\project.exe</outfile>
  <errTitle></errTitle>
  <cmdLine></cmdLine>
  <chdir>.</chdir>
  <priority>normal</priority>
  <downloadUrl>https://adoptopenjdk.net/</downloadUrl>
  <supportUrl></supportUrl>
  <stayAlive>false</stayAlive>
  <restartOnCrash>false</restartOnCrash>
  <manifest></manifest>
  <icon></icon>
  <classPath>
    <mainClass>com.organisation.mavenproject3.Main</mainClass>
    <cp>%classpath com.organisation.mavenproject3.Main</cp>
  </classPath>
  <jre>
    <path></path>
    <bundledJre64Bit>false</bundledJre64Bit>
    <bundledJreAsFallback>false</bundledJreAsFallback>
    <minVersion>11</minVersion>
    <maxVersion>14</maxVersion>
    <jdkPreference>preferJre</jdkPreference>
    <runtimeBits>64/32</runtimeBits>
  </jre>
</launch4jConfig>
```

 i guess error come from the cp option. 
Can i specify it on javapacker ?

**Comment by fvarrui** [comment] 2020-07-10 23:48
I see that you have configured the property `dontWrapJar` to `true`, so jar is not included inside the exe file. This is a proposed solution when using very large jar files with launch4j. Maybe is this the difference?

**Comment by fvarrui** [comment] 2020-07-10 23:53
And, no, you can’t specify `cp` option for launch4j right now, but it’s possible to include mainclass in `cp` by default or include a new plugin option. I don't think adding it affects other developers

**Comment by fvarrui** [comment] 2020-07-12 09:13
I've added mainclass to classpath by default to launch4j and published to 1.1.1-SNAPSHOT. Can you give it a try? 
> :warning: You have to install the plugin manually to your local repo.

**Comment by HumanG33k** [comment] 2020-07-15 07:56
hello, 
sry i hqve been busy, i try but i have an error with the main class for the gradlew.bat

**Comment by fvarrui** [comment] 2020-07-15 22:26
Ok! I’ve been making changes trying yo build and release the plugin with Gradle. I’ll try to build it on a brand new virtual machine to reproduce your problem

**Comment by HumanG33k** [comment] 2020-07-18 19:18
@fvarrui did you test in virtual machine ? I really curious about if this problem came from my setup.

**Comment by fvarrui** [comment] 2020-07-19 01:18
Hi @HumanG33k!
I've just tested in a VM and managed to reproduce your issues:

- Gradle jar was included in `.gitignore` by mistake 😅 ... it's already uploaded to the repo.
- It took `ossrhUser` and `ossrhPassword` properties from `$HOME/.gradle/gradle.properties` file, needed to release the plugin to Maven Central, but not to release to your local repo .... so, now if these properties are not found because this file doesn't exist, it uses empty strings, so it doesn't fail.
- Some dependencies needed for **maven-embeder** were missing, so it couldn't download dependencies from Maven Central. I didn't experience these problems because I already had such dependencies in my local Maven repository.

I hope now you can build and publish SNAPSHOT version to your local repo.

**Comment by HumanG33k** [comment] 2020-07-28 08:40
the build and the publish work but i have some jni error when i execute my jar/exe i will investigate.

**Comment by fvarrui** [comment] 2020-08-11 11:06
Maybe it could be related to this Launch4j [issue](https://sourceforge.net/p/launch4j/bugs/182/). 

I could add a new property to choose if JAR has to be wrapped into EXE or stay next to it, if this is the problem.

**Comment by HumanG33k** [comment] 2020-08-12 13:29
it's probably the case.
i think you already did that work but you should have 
- an association table for common option (behavior is probably more appropriate) 
- a way to specify option by sub tools

**Comment by fvarrui** [comment] 2020-08-13 10:10
> it's probably the case.
> i think you already did that work but you should have
> 
> * an association table for common option (behavior is probably more appropriate)

There are a [samples page](https://github.com/fvarrui/JavaPackager/blob/master/docs/plugin-configuration-samples.md), with different use cases. I have to add more.

> * a way to specify option by sub tools

I’m not sure what you mean.

> * and if time use your tool for already existing java libre software for add more test cases and promote your tool which is really cool at global project scope.

Good idea!! Thanks

> 
> Also for my previous test program, exe are well generated but not find the main class even if my jar work with simple
> 
> ```shell
> java -jar myfat.jar
> ```

If you ceate a mock project, similar to yours, maybe I could help.

**Comment by HumanG33k** [comment] 2020-08-13 14:05
> > * a way to specify option by sub tools
> 
> I’m not sure what you mean.
 
the creation on windows need inno setup and WiX. And both have probably their own options. And had a way to specify throught your config part their options.

Also you if you can (money skills time) build or use a CI stack to auto build your project and the projects use your project.

**Comment by fvarrui** [comment] 2020-08-15 13:52
> > > * a way to specify option by sub tools
> > 
> > 
> > I’m not sure what you mean.
> 
> the creation on windows need inno setup and WiX. And both have probably their own options. And had a way to specify throught your config part their options.

Ok, I get you ... but **Inno Setup** and **WIX** are too complex to contemplate all their variants. For this reason, I enabled the possibility of adding custom options to the plugin through the `extra` property and creating custom templates. However, when there is a common and useful option, I try to add it to the plugin ... as `wrapJar` property, for example.

> 
> Also you if you can (money skills time) build or use a CI stack to auto build your project and the projects use your project.

Yes, it's a good idea! When I have a little more time, I'd like to add test cases to the plugin.

> 
> Your example page is really good it permit a fast learning curve (not sure of the sentence) maybe a back link at the end to option list.
> 
> If you have the time to add the option to not bundle it can be great.

Yes, I'll do it.

**Comment by fvarrui** [comment] 2020-08-16 02:09
`wrapJar` property added to `winConfig` in **1.2.0-SNAPSHOT**, which requires a manual installation.

**Comment by fvarrui** [comment] 2020-09-16 11:16
I've just released v1.2.0 to Maven Central with the new `winConfig.wrapJar` property.
Have you been able to test it?

**Comment by fvarrui** [comment] 2020-09-21 10:34
I'm going to close this issue ... if it's not resolved, we can reopen it and further investigate the cause.
Thx!

**Closed by fvarrui** 2020-09-21 10:34 UTC

**Comment by Trylam** [comment] 2020-09-28 14:26
Hi, 
I am taking over the project instead of  HumanG33k.
When i try, i have an exception : Module java.activation not found, required by java.xml.soap

**Comment by fvarrui** [comment] 2020-09-28 15:42
Hi @Trylam!
I've opened a new issue.
Regards
