### ISSUE TITLE
Signature fail on Mac (even if entitlement file is specified)

### ISSUE THREAD

**Issue by amariottini** [fvarrui/JavaPackager#314] opened 2023-03-28 12:40 UTC
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Signature fail on Mac, it seems that the path to .app is wrong

**Steps to reproduce the issue/enhancement:**
Enable signature:
```
macConfig {
        codesignApp = true
        developerId = "XXXXXXXXXX"
        hardenedCodesign = true
        generatePkg = false
        volumeName = "MyVolumeName"
        entitlements = file("${projectDir}/assets/mac/entitlements.plist")
    }
```

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
```
Executing command: /bin/sh -c cd '/Users/andrea/Projects/projectname/.' && 'find' /Users/andrea/Projects/projectname/build/projectname/projectname.app -depth -type f -exec codesign -f -o runtime -s XXXXXXXXXX --entitlements /Users/andrea/Projects/projectname/assets/mac/entitlements.plist {} \;
    /Users/andrea/Projects/projectname/build/projectname/projectname.app/Contents/MacOS/universalJavaApplicationStub: code object is not signed at all
    In subcomponent: /Users/andrea/Projects/projectname/build/projectname/projectname app/Contents/PlugIns/jre/Contents/Home/LICENSE
    /Users/andrea/Projects/projectname/build/projectname/projectname.app/Contents/PlugIns/jre/Contents/Home/bin/unpack200: replacing existing signature
    /Users/andrea/Projects/projectname/build/projectname/projectname.app/Contents/PlugIns/jre/Contents/Home/bin/jfr: replacing existing signature
    /Users/andrea/Projects/projectname/build/projectname/projectname.app/Contents/PlugIns/jre/Contents/Home/bin/rmid: replacing existing signature
......
......
Executing command: /bin/sh -c cd '/Users/andrea/Projects/projectname/.' && 'codesign' -f -o runtime --entitlements /Users/andrea/Projects/projectname/assets/mac/entitlements.plist -s XXXXXXXXXX /Users/andrea/Projects/projectname/build/projectname
    /Users/andrea/Projects/projectname/build/projectname: bundle format unrecognized, invalid, or unsuitable
```
It seems that the last command is missing the application name, shouldn't it be Users/andrea/Projects/projectname/build/projectname/projectname.app?

**Please tell us about your environment:**
IntelliJ 2022.3.3
Gradle 7.6

- JavaPackager version: 1.7.0
- OS version: MacOS 10.15.7
- JDK version: 11.0.10
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment] 2023-03-28 12:55
Hi again @amariottini!
The problem is not related to entitlements but codesigning.

Please, try this:

1. Build and install the SNAPSHOT version:

```bash
git clone https://github.com/fvarrui/JavaPackager --branch devel
cd JavaPackager
./gradlew publishToMavenLocal
```
> You should build it with Java 11 (this is not a problem for you, as I've seen that is your current JDK)

2. Change your `build.gradle` to use JP `1.7.1-SNAPSHOT`.

3. Try to build your app again.

Plaese, give me some feedback.
Thanks!

**Comment by amariottini** [comment] 2023-03-28 13:05
Yes it works! Thank you.

When do you plan to release version 1.7.1?

**Comment by fvarrui** [comment] 2023-03-28 13:19
I'm closing other pending issues ... I hope it can be released soon!

**Comment by EasyG0ing1** [comment] 2023-04-04 20:48
@fvarrui I've been clicking along with my local compile ... is there anything I might be able to do to help you with getting module support into the library? I don't have a lot of in-depth knowledge on the topic outside of using modules, but I'm a quick study.

**Comment by amariottini** [comment] 2023-05-03 13:50
> I'm closing other pending issues ... I hope it can be released soon!

@fvarrui , any news?

**Comment by fvarrui** [comment] 2023-05-04 11:24
Hi @amariottini!
I've just released 1.7.1 to Maven Central.
Sorry for the delay!!

**Closed by fvarrui** 2023-05-04 11:24 UTC
Labels: bug, duplicate, fixed

**Comment by fvarrui** [comment] 2023-05-05 13:18
> With version 1.7.1 I have this problem: **>Plugin with id 'io.github.fvarrui.javapackager.plugin' not found.**
> 
> Gradle downloads the plugin from Maven but can't activate it. This is in my build.gradle (Gradle version = 7.6):
> 
> ```
> buildscript {
>     repositories {
>         mavenCentral()
>     }
>     dependencies {
>         classpath 'io.github.fvarrui:javapackager:1.7.1'
>     }
> }
> plugins {
>     id 'application'
>     id 'org.jreleaser.jdks' version '1.5.1'
> }
> 
> apply plugin: 'io.github.fvarrui.javapackager.plugin'
> ```
> 
> Do you prefer I open another issue?

No, don't worry ... I realized that there was a missing file in JavaPackager's JAR needed for Gradle plugins (`META-INF/gradle-plugins/io.github.fvarrui.javapackager.plugin.properties`), and I've just released a new version (1.7.2) ... please, could you try this one?

Sorry, this bug was introduced because we upgraded the `build.gradle` in order to support newer Gradle versions (>=8) and something was wrong, but I think that now it's fixed.

**Comment by amariottini** [comment] 2023-05-05 13:28
Version 1.7.2 loads the plugin.
Has still the issue #315.

**Comment by fvarrui** [comment] 2023-05-06 07:40
> Version 1.7.2 loads the plugin. Has still the issue #315.

Please, try `1.7.3-20230505.163915-1` SNAPSHOT version and give some feedback.

**Comment by amariottini** [comment] 2023-05-08 06:35
1.7.3-20230505.163915-1 solves all my issues.
