### ISSUE TITLE
Mac App States "it is damaged" when trying to run

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#69] opened 2020-11-01 02:23 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
App fails to open. Some googling implies that it is because it is [modified after the signing process is done](https://macreports.com/app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash-fix/), though I don't know if that is the actual cause. I haven't tested signing the app packages with a dev key, nor have I determined if the fault lies in Actions' zipping of the app.

**Steps to reproduce the issue/enhancement:**

1. Download the app and try to open it

**What is the expected behavior?**
It would open normally.

**What is the current behavior?**
It doesn't open until you unquarantine it.

**Please tell us about your environment:**

- JavaPackager version:1.4.0-SNAPSHOT
- OS version:MacOS 10.15
- JDK version:15
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
Example app: https://github.com/keastrid/astroimagej/actions/runs/339679738

**Comment by keastrid** [comment] 2020-11-05 02:39
Turns out that Mac places it into quarantine and isn't explicit about that in its message. Not only signing but notarizing the app must be done for it to load without issue.

**Comment by fvarrui** [comment] 2020-11-05 16:52
I have added a new property to specify the signing identity: `macConfig.signingIdentity`, but you must have an Apple Developer ID cert installed on your system to sign your app, and then notarize it. I'm not sure if last step can be automated. I must say that I'm not familiar with all this process.

**Comment by keastrid** [comment] 2020-11-05 18:07
Managed to successfully sign and notarize it.
A couple things are missing by default in JavaPackager: passing an entitlements file to `codesign`. As for notarizing, it can be done with [altool](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow)

**Comment by fvarrui** [comment] 2020-11-05 18:18
Great! Could you give me an example, please?

**Comment by fvarrui** [comment] 2020-11-05 18:20
I've seen that Gatekeeper can be disabled, but for an end user this is not a good idea

**Comment by keastrid** [comment] 2020-11-05 18:29
`xcrun altool --notarize-app --primary-bundle-id com.$APPROOT.dmg \
      -p "@keychain:DEV_PASSWORD" -u "$DEV_ID" --file $APPROOT.dmg`

**Comment by keastrid** [comment] 2020-11-05 18:30
Notarizing can take several minutes, so having something to check in on it that it worked would be good.

**Comment by fvarrui** [comment] 2020-11-06 02:53
Thanks for the info!!!

I don't have an Apple Developer ID certificate and I suppose XCode has to be installed to do this ... I'm using Mac OS 10.12 on a virtual machine for testing and it don't let me install it from the App Store (only 10.15 or above), so I won't can test this functionality when implemented ... I'll have to implement it blindly 🤦‍♂️ What a mess!! 😅

**Comment by fvarrui** [comment] 2020-11-06 11:57
Let's recap: if you have to do it with a BASH script ... do you think it looks like the next?

```bash
#!/bin/bash
# upload and notarize your app binary files with altool

DMG_PATH="/full/path/to/file.dmg"
APP_ID="com.full.path.to.file.dmg" # it has to start with "com."?
DEV_ID="My Apple Developer ID??"
DEV_PASSWORD="password|@keychain:secret|@env:secret"

# notarize the app
xcrun altool --notarize-app --primary-bundle-id $APP_ID -p "$DEV_PASSWORD" -u "$DEV_ID" --file $DMG_PATH

# attach notarization ticket to the app
xcrun stapler staple $DMG_PATH

# retrieves status
xcrun altool -p "$DEV_PASSWORD" -u "$DEV_ID" --notarization-info RequestUUID???
```
> where does "RequestUUID" come from? Is it returned by the notarization command?

Last question: do you think that a generic entitlements file could be generated or it's better that it has to be provided by the developer? (or both possibilities can be contemplated)

Please, let me know if this is right. 

Thanks so much!!!

**Comment by fvarrui** [comment] 2020-11-06 18:28
I've just released [v1.4.0](https://search.maven.org/artifact/io.github.fvarrui/javapackager/1.4.0/jar) to Maven Central.

I've finally renamed `macConfig.signingIdentifier` as `macConfig.developerId`, and added `macConfig.entitlements` property to specify entitlements PList file, both optional and used when signing.

We'll discuss whether notarization should be part of JavaPackager or not.

Thanks a lot for your help!!!

**Comment by fvarrui** [comment] 2020-11-06 18:34
I forgot it! `PackageTask` already has `outputs.upToDateWhen { false }` by default.

**Comment by keastrid** [comment] 2020-11-12 01:38
Sorry for the delay. 
RequestID is the output id from `xcrun altool --notarize-app --primary-bundle-id com.$APPROOT.dmg \
      -p "@keychain:DEV_PASSWORD" -u "$DEV_ID" --file $APPROOT.dmg`

I think a generic entitlements file would be good. Speaking of entitlements, I get "can't set entitlements to null" when the file exists and gradle can find it. `File enFile = file("${projectDir}/packageFiles/aij_entitlements.txt")
    if (enFile != null) {
        macConfig.entitlements = enFile
    }`

As for notarizing, I am unsure as well.

Ah, if it sets upToDate already I can remove those.

**Comment by fvarrui** [comment] 2020-11-13 00:23
> RequestID is the output id from `xcrun altool --notarize-app --primary-bundle-id com.$APPROOT.dmg \ -p "@keychain:DEV_PASSWORD" -u "$DEV_ID" --file $APPROOT.dmg`

👍 

> I think a generic entitlements file would be good. 

I'll take a look to see how It can be done.

> Speaking of entitlements, I get "can't set entitlements to null" when the file exists and gradle can find it. `File enFile = file("${projectDir}/packageFiles/aij_entitlements.txt") if (enFile != null) { macConfig.entitlements = enFile }`

I'm not able to reproduce your issue. I've been testing with the next entitlements file and it's working fine:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>application-identifier</key>
    <string>io.github.fvarrui.helloworld.gradle</string>
</dict>
</plist>
```

Are you sure this is right?
```groovy
File enFile = file("${projectDir}/packageFiles/aij_entitlements.txt")
```
I do it this way:
```groovy
File enFile = project.file('packageFiles/aij_entitlements.txt')
```

![image](https://user-images.githubusercontent.com/4354486/99012434-488bec00-2546-11eb-997b-2b0f9f2f9446.png)

> 
> As for notarizing, I am unsure as well.

I can try to add this functionality as something optional, which has to be enabled with a boolean property, but I need you to test it for me. 

> 
> Ah, if it sets upToDate already I can remove those.

Yes!

**Comment by keastrid** [comment] 2020-11-13 01:35
Entitlements file issue was that I was setting it in `packageAijForMac` instead of in  `javapackager` - so the timing of it finding the file was apparently off (Gradle did recognize the file existed (the `if` shows that)).

[This is the entitlements file we are using.](https://github.com/keastrid/astroimagej/blob/master/packageFiles/aij_entitlements.txt)

**Comment by fvarrui** [comment] 2020-11-13 13:11
If you specify the `macConfig` property both in `javapackager` extension and the task, this last one will be used. All configuration set in `javapackager.macConfig` will be overwritten by `task.macConfig`. They are not merged. If `macConfig` is not specified when defining the task, it uses `javapackager.macConfig` if exists. It was maybe the cause.

**Comment by fvarrui** [comment] 2020-11-13 13:19
I've seen this (**DMG creation fails since it finds one in assets**) in your `build.gradle`:
```groovy
task packageAij(dependsOn: [ packageAijForLinux, packageAijForMac, packageAijForWindows ]) {
    group 'AstroImageJ Developement'

    outputs.upToDateWhen { false }

    doLast { // Cleanup loose files (DMG creation fails since it finds one in assets)
        //project.delete(files("${buildDir}/distributions/assets"))
        //project.delete(files("${buildDir}/distributions/AstroImageJ"))
    }
}
```
It was fixed in 1.4.0, adding `-ov` (overwrite) argument when calling `hdiutil`, because as your comment points, if DMG file exists hdiutil fails. I see that your code is commented, but I'm telling you just in case.

**Comment by keastrid** [comment] 2020-11-14 01:29
Ah, that might be the issue for it not getting the file then.

I saw that it was fixed in the patch notes. It was commented out as the dmg was staying in those folders so deleting them was counter productive.

**Comment by fvarrui** [comment] 2020-11-14 10:54
One question: Does notirizing the app work in background? As you said, it takes several minutes.

```shell
# notarize the app
xcrun altool --notarize-app --primary-bundle-id $APP_ID -p "$DEV_PASSWORD" -u "$DEV_ID" --file $DMG_PATH
```
Is this the cause we need to verify it?
```shell
# retrieves status
xcrun altool -p "$DEV_PASSWORD" -u "$DEV_ID" --notarization-info RequestUUID???
```

**Comment by keastrid** [comment] 2020-11-14 22:06
It should work in the background. The second command retrieves its status. Once complete, `xcrun stapler staple $APPROOT.dmg` is run to finish the notarization.

**Comment by fvarrui** [comment] 2022-07-12 16:10
I don't plan to include app notarization, so I'm going to close this issue. 1.6.7-SNAPSHOT generates a default entitlements file when signing if it's not specified. Thanks!

**Closed by fvarrui** 2022-07-12 16:10 UTC
Labels: bug, help wanted
